### ISSUE TITLE
correct_chirality_for_folder interface should be consistent with Scikit-Learn Transform interface

### ISSUE THREAD

**Issue by paul-reiners** [DCAN-Labs/BIBSnet#1]
Create a class and implement three methods: `fit() `(returning `self`), `transform()`, and `fit_transform()`.

See page 68 of _Hands-on Machine Learning with Scikit-Learn, Keras & TensorFlow_ (2nd edition).

Do the same with the cropping code, which I can't find at the moment.  That should be a separate issue.

**Comment by audreymhoughton** [comment]
Resolved. The chirality correction works. It doesn't use these methods, but it doesn't need to.
