### ISSUE TITLE
odd behavior of preBIBSnet with newborn subject from WashU

### ISSUE THREAD

**Issue by moser297** [DCAN-Labs/BIBSnet#10]
This is a more detailed explanation of the issue that was arising last week. If you would like to follow up on it (not urgent) I can provide you with paths to all the relevant in-/ and outputs. I'm posting this issue for documentation purposes, in case something similar arises again in the future (my problem for this particular subject is solved, using additional manual interventions). 

1. preBIBSnet "final" files from the two different paths (xfms and ACPC) show different amounts of cropping (one still has shoulders, the other one doesn't)
2. For input to BIBSnet xfms path is chosen even though ACPC path has way better alignment when visually comparing both. Is there a way to find the dice coefficient on which this selection is based?

**Comment by ericfeczko** [comment]
sounds good, we'll probably get to this after the initial launch.

Just for clarification -- which one doesn't show cropping, xfms or ACPC?

**Comment by moser297** [comment]
Both of them show cropping but not to the same extend. xfms does the cropping as specified in the .json (brain size z) and ACPC keeps a bit more of the image (in this case a part of the shoulders).

**Comment by audreymhoughton** [comment]
There's a flag to specific brain z size now. This should be resolved.
