### ISSUE TITLE
Clarification on GPU Requirement

### ISSUE THREAD

**Issue by scott-huberty** [DCAN-Labs/BIBSnet#110]
### A short summary of a question you have for the BIBSnet development team.

The [docs](https://bibsnet.readthedocs.io/en/stable/usage/) say:

> [BIBSnet](https://github.com/DCAN-Labs/BIBSnet) can only be run with a GPU, and cannot currently be run with a CPU. BIBSnet needs a Volta (v), Ampere (a), or Turing (t) NVIDIA GPU.

IIRC we've run BIBSNET (when it was tied to CABINET) on machines with other types of GPU's (I think AMD Radeon).  I'm wondering if this NVIDIA GPU requirement is a hard dependency for a specific reason, or whether it's the maintainers saying, '_we've only tested BIBSNet on Machines with NVIDIA GPU's and so can only offer support for machines with NVIDIA GPU's_" ?

Thanks! You can close this ticket when you wish to.

**Comment by LuciMoore** [comment]
@tjhendrickson after talking with @paul-reiners I believe this is correct and it would be more accurate to say that BIBSNet should work on these GPUs (as opposed to the current language that implies a hard dependency). Let me know if you would like me to update this!

**Comment by LuciMoore** [comment]
documentation has been updated to clarify - https://bibsnet.readthedocs.io/en/latest/usage/
