### ISSUE TITLE
Change Parameter File from Being Subject/Session Specific to Study Specific

### ISSUE THREAD

**Issue by tjhendrickson** [DCAN-Labs/BIBSnet#12]
### A short summary of what you would like to see in CABINET.

Currently the parameter file that CABINET requires to run needs the user to specify the BIDS folder, output folder, and subject/session IDs. While this works okay for processing a few subjects/sessions this does not scale well as a unique parameter file is needed per subject/session. 

I propose that the BIDS folder, output folder and subject/session IDs parameters are removed from the parameter file and instead inserted as required command line arguments. This will allow CABINET to run more programmatically at scale. 

### Do you have any interest in helping implement the feature?

Yes!

**Comment by audreymhoughton** [comment]
This was resolved. Only one parameter file is needed per study. We have provided one for the container and one for the app within the repository. Subject and session are now command-line arguments.
