### ISSUE TITLE
Recent change to the name of output mask files

### ISSUE THREAD

**Issue by erikglee** [DCAN-Labs/BIBSnet#120]
### What happened?

Hello, I am looking at the outputs from a new version of the Bibsnet container (release-3.4.0) and it seems like one of the files is named differently than what I have previously encountered. I have pasted the old/new file names below. For reference, it is just this single nifti file that has a new file name. The JSON that corresponds with this nifti still has a naming pattern that matches with the old naming schema. I am guessing this is a bug, so wanted to let you know!

Old file name: sub-102283_ses-V02_space-T2w_desc-brain_mask.nii.gz
New file name: sub-102283_ses-V02_space-T2w_desc-aseg_dseg_T2_mask.nii.gz

### What command did you use?

```shell
singularity run bibsnet.sif /in /out participant
```

### What version of BIBSnet are you using?

release-3.4.0

**Comment by scott-huberty** [comment]
I've noticed this too. 

It looks the nifti filename is generated here (the new naming scheme):

https://github.com/DCAN-Labs/BIBSnet/blob/ace7a360b19507573e48c14024442f354b2289ec/src/postbibsnet.py#L116-L118

After searching with `git grep` it appears that this new naming scheming was introduced a while ago in #51, and then moved to `postbibsnet.py`  in #83 , where it lives now.

For what it is worth,  The [docs](https://github.com/DCAN-Labs/BIBSnet/blob/main/docs/outputs.md) still refer to the "old" naming scheme, when describing BIBSnet outputs.


@erikglee I'm not sure if you were just using a really old version of BIBSnet, or if something changed in the code base that makes BIBsnet hit that aforementioned line for your file, when it didn't before?

**Comment by LuciMoore** [comment]
Resolved in release 3.4.1 by https://github.com/DCAN-Labs/BIBSnet/pull/121
