### ISSUE TITLE
Add test data

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/BIBSnet#135]
### A short summary of what you would like to see in BIBSnet.

add some test data for NMIND certification - maybe some defaced BCP subjects? 

### Do you have any interest in helping implement the feature?

Yes!

**Comment by scott-huberty** [comment]
@LuciMoore what do you think about the little test file I used in https://github.com/DCAN-Labs/BIBSnet/issues/133#issuecomment-2330389207 ?

i.e.


```python

# Python
from pathlib import Path
import openneuro

Path("./ds004776").mkdir()

openneuro.download(dataset="ds004776", target_dir="./ds004776", include="sub-01")
```

```bash
singularity run --nv --cleanenv --no-home \
	-B /path/to/ds004776:/input \
	-B /path/to/derivatives:/output \
	/path/to/bibsnet.sif \
	/input /output participant \
	-participant 01 \
```

**Comment by LuciMoore** [comment]
@scott-huberty sorry I missed your message. yes I think this is a good idea!

**Comment by LuciMoore** [comment]
added Scott's rec to documentation (Testing at end of [Usage](https://bibsnet.readthedocs.io/en/latest/usage/) section) https://github.com/DCAN-Labs/BIBSnet/commit/fa8864c29146814d6388966e4818a729a0035597
