### ISSUE TITLE
permission error while using the latest image. 

### ISSUE THREAD

**Issue by scott-huberty** [DCAN-Labs/BIBSnet#138]
I received a permission error while using the latest image too. Any solution to resolve this?

_Originally posted by @shreyagudapati9 in https://github.com/DCAN-Labs/BIBSnet/issues/132#issuecomment-2352504438_

@shreyagudapati9 Can you copy and paste the stack trace for the permission error?

**Comment by shreyagudapati9** [comment]
@scott-huberty 
<img width="1089" alt="Screenshot 2024-09-19 at 4 42 09 PM" src="https://github.com/user-attachments/assets/59f4154e-4bf3-4875-9ce8-657801a3d42c">

**Comment by scott-huberty** [comment]
@shreyagudapati9  Have a look at my instructions in https://github.com/DCAN-Labs/BIBSnet/issues/132#issue-2497628248

and see if you can enter the image and check the permissions of that file `models.csv`. Feel free to share them here.

**Comment by shreyagudapati9** [comment]
@scott-huberty Thank you! Checked the permissions and this is what it shows :
`-rwxrwx--- 1 root root 713 Aug 14 12:28 /home/bibsnet/data/models.csv`

**Comment by scott-huberty** [comment]
@shreyagudapati9 Looks like you don't actually have the latest image, probably because you have an image with the tag `latest` in your cache and so docker/singularity doesn't actually pull the updated `latest` image from docker hub. Try this:

```bash
docker pull dcanumn/bibsnet:release-3.4.2
```
(replace `docker` with `singularity` as needed)

Then make sure you point to this image when you run BIBsnet. The permissions on this image should be more permissive (I just confirmed this locally):

```bash
docker run -it --entrypoint /bin/bash dcanumn/bibsnet:release-3.4.2
```

```bash

 ls -l /home/bibsnet/data/
```

```console

drwxrwsr-x 1 77661 12710 4096 Aug 26  2022 MNI_templates
-rwxrwxr-x 1 77661 12710 1370 Aug 26  2022 age_to_avg_head_radius_BCP.csv
-rwxrwxr-x 1 77661 12710  295 Aug 26  2022 dataset_description.json
-rwxrwxr-x 1 77661 12710   32 Aug 26  2022 identity_matrix.mat
drwxrwsr-x 1 77661 12710 4096 Aug 26  2022 look_up_tables
-rwxrwxr-x 1 77661 12710  713 Aug 14 16:28 models.csv
-rwxrwxr-x 1 77661 12710  295 Mar 28 21:29 sidecar_template.json
```

**Comment by LuciMoore** [comment]
thanks @scott-huberty !

**Comment by LuciMoore** [comment]
@shreyagudapati9 did you run into any more errors using the latest version?

**Comment by scott-huberty** [comment]
@shreyagudapati9 did this solve your issue? Let us know if you are still having problems, otherwise I'll close this ticket at the end of the week.

**Comment by scott-huberty** [comment]
Closing. @shreyagudapati9 feel free to open another issue if you need to.
