### ISSUE TITLE
"uname": executable file not found in $PATH error message using BIBSnet 3.0.0 on Singularity CE 4.2.1

### ISSUE THREAD

**Issue by sb8498** [DCAN-Labs/BIBSnet#144]
### What happened?

Hi! I am trying to run BIBSnet on my Linux 22.04 GPU PC using singularity CE 4.2.1. I get the error message "uname": executable file not found in $PATH and the container exits.

I have tried to include as much information as possible in this issue. Please let me know if you need any further information. Thank you!

### What command did you use?

```shell
singularity run \
-B /home/devcogpsy/MOTOSO_MRIs/OUTPUT_NIFTI/MOTOSO_sub06:/bids_dir \
-B /home/devcogpsy/MOTOSO_MRIs/OUTPUT_NIFTI/derivatives/bibsnet:/output_dir \
/home/devcogpsy/singularity-ce-4.2.1/bibsnet.sif \
-participant MOTOSO_sub06 \
-start prebibsnet \
-end postbibsnet \
-w /output_dir/work_dir \
-v \
/bids_dir /output_dir participant
```

### What version of BIBSnet are you using?

3.0.0

### Directory Structure

Directory tree for my files

/home/devcogpsy/MOTOSO_MRIs/OUTPUT_NIFTI
├── derivatives
│   └── bibsnet
│       └── work_dir
├── MOTOSO_sub06
│   ├── ses-1
│   │   ├── anat
│   │   │   ├── MOTOSO_sub06_ses-1_run3-T1w.json
│   │   │   ├── MOTOSO_sub06_ses-1_run3-T1w.nii
│   │   │   ├── MOTOSO_sub06_ses-1_run5-T2w.json
│   │   │   └── MOTOSO_sub06_ses-1_run5-T2w.nii
│   │   ├── dwi
│   │   │   ├── dMRI_b0_intro_13.bvec
│   │   │   ├── dMRI_b0_intro_13.nii
│   │   │   ├── dMRI_dir98_AP_1018.nii
│   │   │   ├── dMRI_dir98_AP_16.bvec
│   │   │   ├── dMRI_dir98_AP_16.nii
│   │   │   ├── dMRI_dir98_AP_18.bvec
│   │   │   ├── dMRI_dir98_AP_18.nii
│   │   │   ├── dMRI_dir98_B0_Inv_14.bvec
│   │   │   ├── dMRI_dir98_B0_Inv_14.nii
│   │   │   ├── dMRI_dir98_B0_Inv_15.bvec
│   │   │   └── dMRI_dir98_B0_Inv_15.nii
│   │   └── func
│   │       ├── rfMRI_REST_AP_11.nii
│   │       ├── rfMRI_REST_AP_12.nii
│   │       ├── rfMRI_REST_AP_8.nii
│   │       └── rfMRI_REST_AP_9.nii
│   ├── SpinEchoFieldMap_AP_6.json
│   ├── SpinEchoFieldMap_AP_6.nii
│   ├── SpinEchoFieldMap_PA_7.json
│   ├── SpinEchoFieldMap_PA_7.nii
│   ├── sub-MOTOSO-run2-T1w.json
│   ├── sub-MOTOSO-run2-T1w.nii
│   ├── sub-MOTOSO-run4-T2w.json
│   └── sub-MOTOSO-run4-T2w.nii
├── parameter_file_singularity_bibsnet.json
└── participants.tsv

I have attached the contents of the file "participants.tsv" as a .ods file and also attached the "parameter_file_singularity_bibsnet.json" file

[parameter_file_singularity_bibsnet.json](https://github.com/user-attachments/files/17803276/parameter_file_singularity_bibsnet.json)
[participants.ods](https://github.com/user-attachments/files/17803289/participants.ods)

### Relevant log output

```shell
VERBOSE 2024-11-18 17:08:18,346: All parameters from input args:
{'common': {'fsl_bin_path': '/opt/fsl-6.0.5.1/bin', 'bids_dir': '/bids_dir', 'overwrite': False, 'work_dir': '/output_dir/work_dir'}, 'bibsnet': {'model': '3d_fullres', 'nnUNet_predict_path': '/opt/conda/bin/nnUNet_predict'}, 'stage_names': {'start': 'prebibsnet', 'end': 'postbibsnet'}, 'optional_out_dirs': {'prebibsnet': None, 'bibsnet': None, 'postbibsnet': None, 'derivatives': '/output_dir'}}

INFO 2024-11-18 17:08:18,346: The pipeline took this long to run successfully: 0:00:00.001140


This is the output I get from the -v (verbose) flag.
```

### Add any additional information or context about the problem here.

The bibsnet.sif file is located inside the singularity folder in home/devcogpsy/singularity-ce-4.2.1
I have already added usr/bin into the $PATH for my PC but it doesn't solve the issue.
I also ran the same command in sudo bash and normal bash and the error persists for both.
I don't have nnu-Net installed yet.

**Comment by LuciMoore** [comment]
Hello. I would definitely recommend running the latest version. It may resolve this issue, is more user-friendly (a parameters json is no longer needed), and will also produce higher quality segmentations. Please let us know if you run into the same error or if it is resolved

**Comment by sb8498** [comment]
Hi! I tried running BIBSnet on Docker instead of Singularity and it worked out (and was less complicated). Thank you for your suggestion, I did end up using the latest version of BIBSnet.
