### ISSUE TITLE
Adding manually corrected segmentations from WashU babies to BIBSnet model 

### ISSUE THREAD

**Issue by moser297** [DCAN-Labs/BIBSnet#17]
### A short summary of what you would like to see in CABINET.

Some attempts to use the 512 BIBSnet model with T1 and T2 weighted images collected at WashU resulted in missing parts in the segmentation. To increase generalizability of the model in the future, it could be helpful to add some manually corrected segmentations of these subjects to the set of images the model is trained on. 

### Do you have any interest in helping implement the feature?

Yes!

**Comment by audreymhoughton** [comment]
We are longer planning to add WashU subjects. Issues were resolved in other ways. We will add manually corrected HBCD subjects in the future.
