### ISSUE TITLE
eta squared bug

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/BIBSnet#18]
### What happened?

Gregory﻿ and I need to calculate eta values for the three other subjects to see where the eta problem is. We originally used sub 1, which wasn't a good test case as it had good alignment in both choices.

### What command did you use?

```shell
the current container
```

### What version of CABINET are you using?

the current container

**Comment by LuciMoore** [comment]
Figured out this wasn't an issue after all - eta squared does indeed calculate which path has better registration
