### ISSUE TITLE
"uname" executable file not found 

### ISSUE THREAD

**Issue by dcdeaniii** [DCAN-Labs/BIBSnet#20]
### What happened?

Tried to run latest singularity container on single participant data. Received "name": executable file not found in $PATH error and the container quit.

### What command did you use?

```shell
run --nv --cleanenv --no-home -B /study/dean_k99/Studies/infmri/processed-data/rawdata:/input -B /local/dean:/output -B /local/dean/cabinet/params.json:/param_file.json cabinet.sif /input /output participant -jargs /param_file.json -participant 001 -ses 01 -age 1  -end postbibsnet -v
```

### What version of CABINET are you using?

latest

**Comment by tikal004** [comment]
This error will appear at the beginning of every run.
It comes from a quirk in handling of a build only ENV variable in our base image `nvcr.io/nvidia/pytorch:21.11-py3`  when transformed into a singularity container.
It won't cause any harm, and is unlikely to change in the future.

**Comment by sb8498** [comment]
Hello! I am facing the same error while trying to run BIBSnet on Singularity 4.2.1 installed on a GPU PC running Linux ubuntu 22.4.
I try running BIBSnet on the command line and I get the same "executable file not found in $PATH error" and the container quits.
Could someone please tell me how to fix this issue?
Thanks a lot!

**Comment by LuciMoore** [comment]
@sb8498 can you please post a new issue and include your run command? Thanks!
