### ISSUE TITLE
Allow user to input different brain z values for T1 and T2 in participants.tsv

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/BIBSnet#22]
### A short summary of what you would like to see in CABINET.

It might be useful in the future to allow different brain-z size inputs for T1 vs T2. Sometimes robustfov is finicky with infant data and might choose different locations for the top of the brain depending on the contrast of the images, so the optimal cropping won't always be the same for T1 and T2 (eg T1 will look fine and T2 is over-cropped)

### Do you have any interest in helping implement the feature?

Yes!

### Add any additional information or context about the request here.

Low priority

**Comment by audreymhoughton** [comment]
Notes: This will now have to be in the sub-{}_sessions.tsv instead of the participants.tsv, as that is where the brain z size is grabbed from now.

**Comment by LuciMoore** [comment]
no longer relevant with new cropping logic
