### ISSUE TITLE
Support for sessions tsv files

### ISSUE THREAD

**Issue by erikglee** [DCAN-Labs/BIBSnet#27]
### A short summary of what you would like to see in CABINET.

In convos with Cecile, Tim and I have realized that it is not BIDS valid to have multiple lines for a given subject in a participants.tsv file. So for HBCD Cecile will be making sessions tsv files (https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#sessions-file) that will contain the participants age in months at the time of a session. Would it be possible to have CABINET support reading these files to determine a subject's age?

### Do you have any interest in helping implement the feature?

No :(

**Comment by audreymhoughton** [comment]
Implemented within tagged release 2.3.0
