### ISSUE TITLE
Add json sidecar to accompany *_space-orig_desc-aseg_dseg.nii.gz files

### ISSUE THREAD

**Issue by erikglee** [DCAN-Labs/BIBSnet#37]
### A short summary of what you would like to see in CABINET.

It would be nice if the files found like bibsnet/*_space-orig_desc-aseg_dseg.nii.gz had an accompanying json file with relevant info for the user. For example, it would be great if there could be a field in this json along the lines of "RegisteredTo" or "IntendedFor" which says which file from the BIDS directory the segmentation is registered to. 

It could also be nice to have summary statistics for different segmented regions here. This could just include the volume of each region in the atlas, but also could include statistics about the signal intensity of voxels within each region (mean, standard deviation, etc).

### Do you have any interest in helping implement the feature?

No :(

**Comment by tikal004** [comment]
CABINET now outputs sidecar jsons as described here:
https://cabinet.readthedocs.io/en/stable/outputs/#sidecar-jsons
released it 2.4.3 #62

will revisit adding more information to these files in the future.

**Comment by tikal004** [comment]
Not closing as we have plans to revisit this in the future

**Comment by LuciMoore** [comment]
@tikal004 can we close this now?

**Comment by tikal004** [comment]
Lets close it.
BIBSnet makes sidecar JSONs, I think we left it open because we didn't populate them with all of the information asked here.
@erikglee do you still want more data in the sidecars? If so lets make it a new issue.
