### ISSUE TITLE
Update readthedocs section on age column of participants.tsv file

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/BIBSnet#39]
### A short summary of what you would like to see in CABINET.

https://cabinet.readthedocs.io/en/stable/participants/

I think we should add a note here to use 1 instead of 0 for age if the subject is a neonate since we don't currently have 0mo templates

we should also explain what happens when the subject age is much older - I assume it just uses the oldest set of templates over a certain age?

### Do you have any interest in helping implement the feature?

Yes!

**Comment by rosemccollum** [comment]
added the note about using 1 as an age. Didn't address what happens when a subject is much older

**Comment by rosemccollum** [comment]
Added note about what happens with older subjects
