### ISSUE TITLE
participants.json / sub-{}_sessions.json

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/BIBSnet#41]
### A short summary of what you would like to see in CABINET.

- require a participants.json or a sub-()_sessions.json to be paired with the participants.tsv and sub-{}_sessions.tsv, respectively
- see BIDS specification for what a participants.json / sub-{}_sessions.json looks like: https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file:~:text=UTF%2D8%20encoding.-,Participants%20file,-Template%3A
- validate that the age columns units are "months" before utilizing the column
- probably also validate the units of the brain_z_size (unsure what these would be)
- if the units do not match what cabinet needs, fail and throw an error telling the user to change the tsv/json to have the correct units in order to be processed through cabinet
- possible that we could convert them, but that might be odd for infants - it is more likely that they accidentally have the wrong units in their paired JSON instead of having infant age in years in their TSV
- it should do this validation at the very beginning when validating parameters in order to fail fastest for the user

### Do you have any interest in helping implement the feature?

Yes!

**Comment by LuciMoore** [comment]
[version 3.4.1](https://github.com/DCAN-Labs/BIBSnet/releases/tag/3.4.1) is no longer age-dependent and so does not rely on these tsv files!
