### ISSUE TITLE
Repository Data Directory

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/BIBSnet#42]
### A short summary of what you would like to see in CABINET.

- add the contents of the data.zip file back into the cabinet repository on github (now that the repository is public, we shouldn't have the space issue we had while it was private)
- remove the dockerfile command to pull the data.zip file from the s3
- will need to test that the container still works with this method before adding it into main
- remove data.zip from the s3 once the container works with it hosted directly within the repository
- we'll then be able to explain and document the template files etc more in the readthedocs (i.e where they came from, how they are used, where the user can find them in the repo if they are curious)
- after this, it would be good to BIDS-ify the template names, but that would involve some code changes too (more of an ask than changing the file names)

### Do you have any interest in helping implement the feature?

Yes!

**Comment by tikal004** [comment]
Based on what @madisoth just did to reduce container size, I don't think we should consider doing this anymore.
This would likely increase the size
