### ISSUE TITLE
Output a separate segmentation in native T2w space (in addition to current output in T1w space)

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/BIBSnet#45]
### A short summary of what you would like to see in CABINET.

Required for Nibabies T2-based surface generation critical for optimal infant processing. I can help implement

### Do you have any interest in helping implement the feature?

Yes!

**Comment by audreymhoughton** [comment]
Output with version 2.4.2 of CABINET. Sidecar JSON implementation is in progress. Will be tracked on this issue: https://github.com/DCAN-Labs/CABINET/issues/37
