### ISSUE TITLE
Exactly one BIBSnet seg file

### ISSUE THREAD

**Issue by ajdneuro** [DCAN-Labs/BIBSnet#57]
### What happened?

Hello I am using the singularity image (most recent) and ran into this error:

INFO 2023-06-19 00:03:32,519: Finished dilating left/right segmentation mask

ERROR 2023-06-19 00:03:32,520: There must be exactly one BIBSnet segmentation file: /workingdir/bibsnet/sub-1007/ses-SCANS/output/*.nii.gz
Resume at postBIBSnet stage once this is fixed.

### What command did you use?

```shell
module purge
module load singularity
singularity run --nv --cleanenv \
-B /projects/b1174/cabinet_test/bidsdir:/input \
-B /projects/b1174/cabinet_test/outdir:/output \
-B /projects/b1174/cabinet_test/param_files/param_file.json:/param_file.json \
-B /projects/b1174/cabinet_test/workingdir:/workingdir \
/projects/b1174/singularity_images/cabinet_2.4.0.sif \
/input /output participant -jargs /param_file.json -end postbibsnet -v -participant 1007 -w /workingdir
```

### What version of CABINET are you using?

2.4.0

### Relevant log output

```shell
NFO 2023-06-19 00:03:32,519: Finished dilating left/right segmentation mask

ERROR 2023-06-19 00:03:32,520: There must be exactly one BIBSnet segmentation file: /workingdir/bibsnet/sub-1007/ses-SCANS/output/*.nii.gz
Resume at postBIBSnet stage once this is fixed.
```

### Add any additional information or context about the problem here.

Thank you!

**Comment by audreymhoughton** [comment]
@ajdneuro was this re-run with the same output and working directories? Without --overwrite, it won't overwrite a previous run.

If not, were there extra segmentation outputs in the bibsnet output directory within the working directory?

**Comment by ajdneuro** [comment]
thank you! using the overwrite flag fixed the issue, thank you for your response and help!!!!!

**Comment by audreymhoughton** [comment]
@ajdneuro awesome - no problem! I will close this issue.
