### ISSUE TITLE
Issues with Segmentation File

### ISSUE THREAD

**Issue by henrycikanek** [DCAN-Labs/BIBSnet#59]
### What happened?

For a handful of our one-month subjects, that have decent quality T1 and T2 images we are observing major issues with the segmentation file created by CABINET whereby the location of the brain regions are very off. We provided an image of a subject that exemplifies this issue. We're noticing this to be an issue more so with the T2 segmentation files. What is surprising is that this isn't happening for all subjects so it is unclear why this is happening for some subjects, but not all. 

### What command did you use?

```shell
docker run -t \
        -v "${input_dir}:/input" \
        -v "${output_dir}:/output" \
        -v "${work_dir}:/work_tmp" \
        -v "${param_file}:/param_file.json" \
        dcanumn/cabinet:2.4.2 \
        /input /output \
        participant \
        -participant "${participant_id}" \
        -ses "${session}" \
        -age "${age}" \
        -jargs /param_file.json \
        -end postbibsnet \
        -start prebibsnet \
        -w /work_tmp \
		-v
```

### What version of CABINET are you using?

2.4.2

### Relevant log output

```shell
No log output. Issues with the final product
```

### Add any additional information or context about the problem here.

![Screen Shot 2023-06-30 at 1 28 12 PM](https://github.com/DCAN-Labs/CABINET/assets/42556168/fc4846c7-6d74-4f9f-951b-a530e9a75c61)

**Comment by audreymhoughton** [comment]
@henrycikanek, were the BIBSnet inputs in alignment before bibsnet? You can check the images in the bibsnet input directory under the cabinet working directory you specified for alignment.

Another option is to remove the T1w images from your inputs to run the T2-only model or the T2w images from your inputs to run the T1-only model. We have seen improvements on some subjects/datasets if we do not use both types of images to generate the segmentation. Ideally, you wouldn't have to remove the files from your input dir to run the different models; that is on the list of features we intend to add.

**Comment by hough129** [comment]
@henrycikanek I am going to close this issue. Please re-open it if the problem persists.

**Comment by audreymhoughton** [comment]
@henrycikanek I am going to close this issue. Please re-open it if the problem persists.

**Comment by yanbin-niu** [comment]
Hi @hough129, thanks for pointing to a solution. I am testing with model 515 (T2w-only). However, it threw an error: 

> CABINET: error: CABINET needs T1w data at the path below to run model 515, but none was found.

docker version: dcanumn/cabinet:2.4.2
parameters: `participant -participant sub-13399 -ses ses-newborn -age 1 -jargs /param_file.json -end postbibsnet -start prebibsnet --model-number 515 -w /work_tmp -v`

Thank you in advance!
