### ISSUE TITLE
Run Nibabies + XCP-D

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/BIBSnet#66]
### A short summary of what you would like to see in CABINET.

Wrap Nibabies and XCP-D to run within CABINET.

### Do you have any interest in helping implement the feature?

Yes!

**Comment by tikal004** [comment]
This is now outside the scope of this codebase, please see [CABINET](https://github.com/DCAN-Labs/CABINET) for running BIBSnet with NiBabies and XCPD.
