### ISSUE TITLE
Is the T2-only Model flag up and running?

### ISSUE THREAD

**Issue by henrycikanek** [DCAN-Labs/BIBSnet#77]
### A short summary of a question you have for the CABINET development team.

We have found with our lab (SEA Lab at Vandy) that we generally get higher quality results from exclusively running the T2-only model. Currently, we have been manually removing our T1s to force bibsnet to use the T2-only model, but I remember I had an issue a few months back and was told this flag was in development, so just wanted to check-in. I looked at the usage page of the docs and saw its mention but wasn't sure yet if it was ready.

**Comment by ericfeczko** [comment]
T2 only model should have been working for quite some time now. That being said, we haven't updated the T2 only model for some time, so subcortical fixes may not be fully incorporated. 

If there were issues with holes in the segmentation, these turned out to be unrelated to the model used and reflected issues in post-processing with BIBSnet (not CABINET).

**Comment by ericfeczko** [comment]
Oh, you were referring to the manual removal of T1s, yeah that hasn't been resolved yet, and likely will within BIBSnet.

**Comment by henrycikanek** [comment]
Thanks for your response. What do you mean in regards to subcortical fixes not being fully incorporated? Do you mean that the T2 & T1 model works better for subcortical segmentation than the T2-only model? Also, what about the cortical regions, are there any differences algorithmically between the two models?

**Comment by LuciMoore** [comment]
Closing this issue for now - all the models were updated a while ago. we were prioritizing training for the T1+T2 models at first, so there was a period of time where the T1- and T2-only models weren't necessarily as up-to-date (ie they were trained on a former iteration of a dataset that didn't have the same quality of segmentations), but that is no longer the case. Please re-open or post a new issue if you have further questions!
