### ISSUE TITLE
Specifying all three stages of segmentation pipeline (preBIBSnet, BIBSnet, postBIBSnet) without previously generated outputs results in error

### ISSUE THREAD

**Issue by tjhendrickson** [DCAN-Labs/BIBSnet#8]
The segmentation pipeline behaves oddly when all three stages are specified start to end in one call. Without any previously run stage if the stages are specified as follows `-start preBIBSnet -end postBIBSnet` the following error is thrown:
`usage: run.py [-h] [-start {preBIBSnet,BIBSnet,postBIBSnet,nibabies,XCPD}]
              [-end {preBIBSnet,BIBSnet,postBIBSnet,nibabies,XCPD}]
              [--script-dir SCRIPT_DIR]
              parameter_json
run.py: error: The file(s) below are needed to run the BIBSnet stage, but they do not exist.
/output/BIBSnet/sub-470437/ses-1mo/input/sub-470437_ses-1mo_optimal_resized_0000
.nii.gz`

It appears that somehow the preBIBSnet routines get skipped here and move right on to the BIBSnet stage, however, when just the preBIBSnet stage is run `-start preBIBSnet -end preBIBSnet` it completes just fine.

**Comment by audreymhoughton** [comment]
I believe this currently works. Closing the issue.
