### ISSUE TITLE
postBIBSnet chirality correction not accurate around midline

### ISSUE THREAD

**Issue by moser297** [DCAN-Labs/BIBSnet#84]
### What happened?

Chirality correction during postBIBSnet is in many cases not accurate around the medial plane (see example image) which causes the MCRIBS surface reconstruction in Nibabies to crash. 

<img width="145" alt="image" src="https://github.com/DCAN-Labs/BIBSnet/assets/90271498/0559db98-d611-46da-a81f-250891402d7e">

### What command did you use?

```shell
# run cabinet 
env -i ${singularity} run \
-B ${data_dir}/:/input \
-B ${out_dir}/:/output \
-B /home/faird/shared/code/external/utilities/freesurfer_license/license.txt:/opt/freesurfer/license.txt \
/home/faird/shared/code/internal/pipelines/cabinet_container/cabinet_shrink_docker_build_plus_clusters_fix_09272023a.sif \
/input /output participant -jargs /home/cabinet/parameter-file-container.json -start prebibsnet -end postbibsnet -v
```

### What version of BIBSnet are you using?

latest

### Add any additional information or context about the problem here.

Happy to help solving this issue as I have plenty of datasets where I'm planning to use the Nibabies MCRIBS workflow combined with BIBSnet.

**Comment by LuciMoore** [comment]
@moser297 this error should be largely ameliorated in the latest version of BIBSNet that includes a corrected 1mo chirality template. @tikal004 is working on incorporating corrected templates for the older ages as well currently

Can you please re-run your data and let us know how they compare?

**Comment by kellyhi08** [comment]
Hello, I am running into a similar problem, where the left/right labeling is going awry. 

Command I am using (I downloaded the latest bibsnet version on Jan 26th): 
`singularity pull bibsnet.sif docker://dcanumn/bibsnet:latest 
singularity run --nv --cleanenv --no-home \
-B $path/BIBSnet_inputs/:/input \
-B $path/BIBSnet_outputs:/output \
$path/BIBSnet/bibsnet.sif \
/input /output participant --participant-label 001`

Any updates or suggestions for fixing this?

**Comment by kellyhi08** [comment]
Image: (subject age= 11 months)

<img width="616" alt="image" src="https://github.com/DCAN-Labs/BIBSnet/assets/63243958/bfbad2a4-4678-41c7-aa4e-45e4347bedcd">

**Comment by LuciMoore** [comment]
Resolved in latest version that no longer produces nnU-Net outputs with chirality errors https://github.com/DCAN-Labs/BIBSnet/releases/tag/3.4.1
