### ISSUE TITLE
Issue running prebibsnet and bibsnet stages, then later running postbibsnet

### ISSUE THREAD

**Issue by erikglee** [DCAN-Labs/BIBSnet#87]
### What happened?

I am trying to run a test where I take a pre-existing run of bibsnet [the container] (which included prebibsnet, bibsnet, and postbibsnet), and then move it to a new location, specify a new output directory, and delete the "postbibsnet" folder under the working directory. Then what I am interested in is restarting bibsnet at the "postbibsnet" stage, taking as input the original BIDS data and the working directory (again, after the postbibsnet folder has been deleted).

When I do this, the "postbibsnet" section of the code gets very close to finishing. But based on the attached error log, it seems like the code is expecting some file to be there that doesn't exist. I don't know if this is because the original derivatives folder and the work/postbibsnet folder had been deleted, or if there is some complication that has come up because the pipeline started populating the working directory under one path (for prebibsnet and bibsnet) and is finishing populating the working directory at another path (for postbibsnet). Or I suppose it could be something else more generic to the process of running the container stage by stage.

Any idea what might be going on and how this could be fixed? 

### What command did you use?

```shell
/usr/bin/singularity run --nv \
-B /home/faird/shared/projects/HBCD_MIDB_IG/cabinet/bibsnet_test_from_barry/roo_data1_eriks_copy/input/:/input \
-B /home/faird/shared/projects/HBCD_MIDB_IG/cabinet/bibsnet_test_from_barry/roo_data1_eriks_copy/derivatives/:/output \
-B /home/faird/shared/projects/HBCD_MIDB_IG/cabinet/bibsnet_test_from_barry/roo_data1_eriks_copy/work/:/work \
/home/faird/shared/code/internal/pipelines/bibsnet_container/bibsnet_clusters-fix-2023.10.16.sif \
/input /output participant -jargs /home/cabinet/parameter-file-container.json -start postbibsnet -end postbibsnet -v \
--participant-label M1003 \
-w /work
```

### What version of BIBSnet are you using?

bibsnet_clusters-fix-2023.10.16.sif

### Relevant log output

```shell
"uname": executable file not found in $PATH
Traceback (most recent call last):
  File "/home/bibsnet/bibsnet", line 48, in <module>
    main()
  File "/home/bibsnet/bibsnet", line 39, in main
    run_all_stages(STAGES, sub_ses_IDs, json_args["stage_names"]["start"],
  File "/home/bibsnet/src/utilities.py", line 223, in run_all_stages
    sub_ses_j_args = stage(sub_ses_j_args)
  File "/home/bibsnet/src/postbibsnet.py", line 73, in run_postBIBSnet
    nii_outfpath = reverse_regn_revert_to_native(
  File "/home/bibsnet/src/postbibsnet.py", line 557, in reverse_regn_revert_to_native
    preBIBSnet_mat = glob(preBIBSnet_mat_glob).pop()
IndexError: pop from empty list
```

**Comment by audreymhoughton** [comment]
![Screenshot 2023-10-19 at 11 16 39 AM](https://github.com/DCAN-Labs/BIBSnet/assets/77338310/038b9e05-253b-4e73-adf7-05e9130c9c8c)
![Screenshot 2023-10-19 at 11 16 49 AM](https://github.com/DCAN-Labs/BIBSnet/assets/77338310/2755ee45-d30b-4ac7-a94b-eee32270a47a)
