### ISSUE TITLE
Turn off post-processing settings for cases where manual segmentation correction has been performed

### ISSUE THREAD

**Issue by erikglee** [DCAN-Labs/BIBSnet#92]
### A short summary of what you would like to see in BIBSnet.

At the moment we are looking into a semi-automated workflow where we first run all of BIBSNET, then we have individuals manually correct the segmentations using the files found in various work directories, and then we plan to restart BIBSNET at the "postbibsnet" stage using the manually corrected segmentations. Because we expect the manual corrections to be "ground truth", we are wondering if a flag could be added that allows users to run "postbibsnet" without any post-processing steps that could reintroduce errors into the segmentation.

At a minimum, I think this would involve the flag turning off (1) chirality correction, and (2) the code that attempts to remove non-brain clusters from the segmentation. I don't know if there are other steps that should potentially be turned off also.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by ericfeczko** [comment]
I wouldn't use BIBSNET on manually corrected segmentations. This seems beyond scope for a program designed for automated segmentation. Sounds like you just need to write a quick function to backproject via the transforms and then just run the next stage of your processing.

**Comment by LuciMoore** [comment]
We've decided to develop a separate utility for this instead of adding this functionality to BIBSNet since it's for a very specific use case, so this issue can be closed: https://github.com/DCAN-Labs/mancorr-postbibsnet
