### ISSUE TITLE
Issue running BIBSnet through singularity

### ISSUE THREAD

**Issue by kellyhi08** [DCAN-Labs/BIBSnet#96]
### A short summary of a question you have for the BIBSnet development team.

Hello,

When running BIBSnet I am getting a KeyError for my subject number (leading me to assume there is an issue with my file structure or naming format).

**Question**
Would it be possible to get an example of the correct file structure to have my data organized in? Currently, I am using BIDS format with the  nnU-Net formatting for T1 and T2 naming.

**Command:** 
singularity pull bibsnet.sif docker://dcanumn/bibsnet:latest (successfully run)
singularity run --nv --cleanenv --no-home -B $path/input/:/input -B $path/output:/output $path//input /output participant -v (errors)

**Information on File organization:** 
My files are organized in the following format

-  path/input
     - participants.tsv
     - sub-007_ses-02
            - sub-007_sessions.tsv
            - anat
                   - sub-007_ses-02_0000.nii.gz (this is the T1)
                   - sub-007_ses-02_0001.nii.gz (this is the T2)

**Text of the error:** 
INFO:    underlay of /etc/localtime required more than 50 (108) bind mounts
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (495) bind mounts
"uname": executable file not found in $PATH
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-bckm4y8b because the default path (/users/PAS1305/kellyhiersche08/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sub-007_ses-02'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bibsnet/bibsnet", line 48, in <module>
    main()
  File "/home/bibsnet/bibsnet", line 33, in main
    json_args, sub_ses_IDs = get_params([get_stage_name(stg) for stg in STAGES])
  File "/home/bibsnet/src/get_args.py", line 180, in get_params
    return validate_cli_args(vars(parser.parse_args()), stage_names,
  File "/home/bibsnet/src/get_args.py", line 264, in validate_cli_args
    sub_ses_IDs[ix]["age_months"] = read_from_tsv(
  File "/home/bibsnet/src/get_args.py", line 444, in read_from_tsv
    col_value = get_col_value_from_tsv(j_args, tsv_df, ID_col, col_name, sub_ses)
  File "/home/bibsnet/src/get_args.py", line 466, in get_col_value_from_tsv
    subj_row = tsv_df.loc[
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3776, in xs
    loc = index.get_loc(key)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'sub-007_ses-02'

Thank you,

Kelly

**Comment by lundq163** [comment]
Hi @kellyhi08,

I would first try splitting up your input directory into separate sub/ses dirs, with the session dir one level below the subject dir, then resubmitting. Your directory structure would look something like this:

- path/input
   - participants.tsv
   - sub-007
        - ses-02
        - sub-007_sessions.tsv
             - anat
                  - sub-007_ses-02_0000.nii.gz (this is the T1)
                  - sub-007_ses-02_0001.nii.gz (this is the T2)

**Comment by kellyhi08** [comment]
Thank you so much! I really appreciate your quick and helpful responses.

I have done that, and now I have a new error (progress!). It seems the program is not identifying the T1 or T2 (see bolded section of error below)

INFO:    underlay of /etc/localtime required more than 50 (108) bind mounts
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (495) bind mounts
"uname": executable file not found in $PATH
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-s5y7_c20 because the default path (/users/PAS1305/kellyhiersche08/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.

VERBOSE 2024-01-16 13:58:32,781: Age in months for Subject sub-007 Session ses-02: 19
Closest BCP age in months in age-to-head-radius table: 19

VERBOSE 2024-01-16 13:58:32,809: /home/bibsnet/bibsnet /input /output participant -v

VERBOSE 2024-01-16 13:58:32,809: All parameters from input args:
{'common': {'fsl_bin_path': '/opt/fsl-6.0.5.1/bin', 'bids_dir': '/input', 'overwrite': False, 'work_dir': '/tmp/bibsnet', 'no_denoise': False}, 'bibsnet': {'model': '3d_fullres', 'nnUNet_predict_path': '/opt/conda/bin/nnUNet_predict'}, 'meta': {'script_dir': '/home/bibsnet', 'slurm': False}, 'stage_names': {'start': 'prebibsnet', 'end': 'postbibsnet'}, 'optional_out_dirs': {'prebibsnet': '/tmp/bibsnet/prebibsnet', 'bibsnet': '/tmp/bibsnet/bibsnet', 'postbibsnet': '/tmp/bibsnet/postbibsnet', 'derivatives': '/output'}}

VERBOSE 2024-01-16 13:58:32,809: All required input files exist.

INFO 2024-01-16 13:58:32,810: Now running prebibsnet stage on:
**{'subject': 'sub-007', 'session': 'ses-02', 'age_months': 19, 'brain_z_size': 161, 'has_T1w': False, 'has_T2w': False, 'model': Series([], Name: model_num, dtype: int64)}**

INFO 2024-01-16 13:58:32,812: The anatomical images have been cropped for use in BIBSnet
Traceback (most recent call last):
  File "/home/bibsnet/bibsnet", line 48, in <module>
    main()
  File "/home/bibsnet/bibsnet", line 39, in main
    run_all_stages(STAGES, sub_ses_IDs, json_args["stage_names"]["start"],
  File "/home/bibsnet/src/utilities.py", line 243, in run_all_stages
    sub_ses_j_args = stage(sub_ses_j_args)
  File "/home/bibsnet/src/prebibsnet.py", line 100, in run_preBIBSnet
    j_args, "flirt", "-in", cropped[t1or2],
**KeyError: 2**

**Comment by lundq163** [comment]
can you add in your new directory structure like you did previously?

**Comment by kellyhi08** [comment]
Yes: 

- $path/input 
     - participants.tsv
     - sub-007
           - sub-007_sessions.tsv
           - ses-02
                -  anat
                      - sub-007_ses-02_0000.nii.gz
                      - sub-007_ses-02_0001.nii.gz

**Comment by lundq163** [comment]
make sure that the `anat` directory is within the `ses-02` directory, and then make sure that the T1 and T2 niftis are within the `anat` directory before resubmitting.

**Comment by kellyhi08** [comment]
Yes, they are. The indenting went away. sub-007 is a folder, then ses-02 is a subfolder, then anat is a subfolder of that, then the nii.gz files. 

It matches the file structure you recommended in your first response.

**Comment by kellyhi08** [comment]
I think I figured it out! I thought I was supposed to use the 0000 and 0001 naming for T1 and T2 during my initial submission, but I should use typical BIDS formatting of sub-X_ses-X_T1w.nii.gz and sub-X_ses-X_T2w.nii.gz, then the preBIBSnet will rename it for me. 

It seems to be working now. Thanks for all your help!

**Comment by lundq163** [comment]
yes good catch! i just noticed that in the code as well. Feel free to make another issue if any error persists
